# Generated by Django 3.1.5 on 2021-01-13 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0001_initial'),
        ('circles', '0002_auto_20210113_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='offered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ride',
            name='offered_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='circles.circle'),
        ),
        migrations.AddField(
            model_name='ride',
            name='passengers',
            field=models.ManyToManyField(related_name='passengers', to=settings.AUTH_USER_MODEL),
        ),
    ]
